server.port=8080

spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/exam_planning_db?createDatabaseIfNotExist=true
spring.datasource.username=sql12827064
spring.datasource.password=mTvStxX8UY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=MALIKsalimovSecretKey20262006
jwt.expiration=86400000